version: '3.8'

services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bndes-lambda-local
    ports:
      - "9000:8080"
    volumes:
      - ./data:/tmp/local_data
    environment:
      - LOCAL_OUTPUT_DIR=/tmp/local_data
